### ISSUE TITLE
install ServiceComb-Java-Chassis 时出错

### ISSUE THREAD

**Issue by zhuhoudong** [ServiceComb/ServiceComb-Java-Chassis#133]
根据我们的快速入门的指南，发现有编译错误。用的是阿里云maven镜像库。

git clone https://github.com/ServiceComb/ServiceComb-Java-Chassis.git
cd ServiceComb-Java-Chassis

只想上述命令是OK的。但是执行下述命令时候，有错误：

mvn clean install -DskipTests -DskipITs

root@ubuntu64:/usr/share/maven/conf# cd /home/zhu/docker-file/ServiceComb-Java-Chassis/
root@ubuntu64:/home/zhu/docker-file/ServiceComb-Java-Chassis# mvn clean install -DskipTests -DskipITs
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /root/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.4.5.RELEASE/spring-boot-dependencies-1.4.5.RELEASE.pom: attribute value must start with quotation or apostrophe not t (position: TEXT seen ...vascript"\r\n\t\t\tsrc="js/visitorAccountApplication/portal.js" defer=t... @14:56)  @ /root/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.4.5.RELEASE/spring-boot-dependencies-1.4.5.RELEASE.pom, line 14, column 56
[FATAL] Non-parseable POM /root/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Camden.SR6/spring-cloud-dependencies-Camden.SR6.pom: attribute value must start with quotation or apostrophe not t (position: TEXT seen ...vascript"\r\n\t\t\tsrc="js/visitorAccountApplication/portal.js" defer=t... @14:56)  @ /root/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Camden.SR6/spring-cloud-dependencies-Camden.SR6.pom, line 14, column 56
[ERROR] 'dependencies.dependency.version' for org.hamcrest:hamcrest-all:jar is missing. @ io.servicecomb:java-chassis-parent:[unknown-version], /home/zhu/docker-file/ServiceComb-Java-Chassis/parent/pom.xml, line 62, column 17
[FATAL] Non-parseable POM /root/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.4.5.RELEASE/spring-boot-dependencies-1.4.5.RELEASE.pom: attribute value must start with quotation or apostrophe not t (position: TEXT seen ...vascript"\r\n\t\t\tsrc="js/visitorAccountApplication/portal.js" defer=t... @14:56)  @ /root/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.4.5.RELEASE/spring-boot-dependencies-1.4.5.RELEASE.pom, line 14, column 56
[FATAL] Non-parseable POM /root/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Camden.SR6/spring-cloud-dependencies-Camden.SR6.pom: attribute value must start with quotation or apostrophe not t (position: TEXT seen ...vascript"\r\n\t\t\tsrc="js/visitorAccountApplication/portal.js" defer=t... @14:56)  @ /root/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Camden.SR6/spring-cloud-dependencies-Camden.SR6.pom, line 14, column 56
[FATAL] Non-parseable POM /root/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.4.5.RELEASE/spring-boot-dependencies-1.4.5.RELEASE.pom: attribute value must start with quotation or apostrophe not t (position: TEXT seen ...vascript"\r\n\t\t\tsrc="js/visitorAccountApplication/portal.js" defer=t... @14:56)  @ /root/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.4.5.RELEASE/spring-boot-dependencies-1.4.5.RELEASE.pom, line 14, column 56
[FATAL] Non-parseable POM /root/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Camden.SR6/spring-cloud-dependencies-Camden.SR6.pom: attribute value must start with quotation or apostrophe not t (position: TEXT seen ...vascript"\r\n\t\t\tsrc="js/visitorAccountApplication/portal.js" defer=t... @14:56)  @ /root/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Camden.SR6/spring-cloud-dependencies-Camden.SR6.pom, line 14, column 56
[ERROR] 'dependencies.dependency.version' for org.hamcrest:hamcrest-all:jar is missing. @ io.servicecomb:java-chassis-parent:[unknown-version], /home/zhu/docker-file/ServiceComb-Java-Chassis/parent/pom.xml, line 62, column 17
以下省略

**Comment by eric-lee-ltk** [comment]
Try executing `rm -rf /root/.m2/repository/org/springframework/` and then rerun the `mvn clean install -DskipTests -DskipITs` command.

**Comment by zhuhoudong** [comment]
@eric-lee-ltk  thanks！It worked！
