### ISSUE TITLE
BMI demo没找着

### ISSUE THREAD

**Issue by hiocs** [ServiceComb/ServiceComb-Java-Chassis#134]
快速入门，“创建第一个微服务”提到
`git clone https://github.com/ServiceComb/ServiceComb-Java-Chassis.git`
目前代码还未更新上去

**Comment by zhuhoudong** [comment]
确实，在sample目录下面没有bmi这个目录。

<img width="416" alt="2017-09-06_162736" src="https://user-images.githubusercontent.com/31299631/30101793-33476146-9320-11e7-8554-e1018a33dc21.png">

**Comment by hiocs** [comment]
期待中。。。

**Comment by zenlinTechnofreak** [comment]
#137 have been resolved this issuse @hiocs

**Comment by zenlinTechnofreak** [comment]
@zhuhoudong  Can u send me a email? my email is zenlintechnofreak@gmail.com. Thx.
