### ISSUE TITLE
NO BMI Source in Github

### ISSUE THREAD

**Issue by zhuhoudong** [ServiceComb/ServiceComb-Java-Chassis#137]
There is no source in github，

samples/bmi

https://github.com/ServiceComb/ServiceComb-Java-Chassis/tree/master/samples/bmi
![image](https://user-images.githubusercontent.com/31299631/30147948-90f729a8-93d3-11e7-8d1a-a8cc15c8c698.png)

**Comment by eric-lee-ltk** [comment]
The BMI sample currently is still in PR. You can get the code with the following commands:
1. `git clone https://github.com/ServiceComb/ServiceComb-Java-Chassis`
2. `cd ServiceComb-Java-Chassis`
3. `git fetch origin pull/129/head:sample`
4. `git checkout sample`

**Comment by eric-lee-ltk** [comment]
@zhuhoudong The url should work now. Thanks for your feedback.
