### ISSUE TITLE
api鉴权机制

### ISSUE THREAD

**Issue by hiocs** [ServiceComb/ServiceComb-Java-Chassis#140]
想了解一下api鉴权机制是怎么做的，是否有例子可以参考？

**Comment by WillemJiang** [comment]
API鉴权在Java Chassis里面没有提供相关的实现， 我们在Company这个示例里面有相关的API通过JWT来进行鉴权的代码。 
https://github.com/ServiceComb/ServiceComb-Company-WorkShop/blob/master/manager/src/main/java/io/servicecomb/company/manager/AuthenticationService.java

**Comment by hiocs** [comment]
好的，谢谢！
