### ISSUE TITLE
BMI compile error

### ISSUE THREAD

**Issue by zhuhoudong** [ServiceComb/ServiceComb-Java-Chassis#145]
root@i-wzmhsx68:/home/ubuntu/ServiceComb-Java-Chassis/samples/bmi# mvn compile

[INFO] Scanning for projects...
Downloading: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/boot/spring-boot-starter-parent/1.4.5.RELEASE/spring-boot-starter-parent-1.4.5.RELEASE.pom
Downloaded: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/boot/spring-boot-starter-parent/1.4.5.RELEASE/spring-boot-starter-parent-1.4.5.RELEASE.pom (0 B at 0.0 KB/sec)
Downloading: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/boot/spring-boot-dependencies/1.4.5.RELEASE/spring-boot-dependencies-1.4.5.RELEASE.pom
Downloaded: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/boot/spring-boot-dependencies/1.4.5.RELEASE/spring-boot-dependencies-1.4.5.RELEASE.pom (0 B at 0.0 KB/sec)
Downloading: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/spring-framework-bom/4.3.7.RELEASE/spring-framework-bom-4.3.7.RELEASE.pom
Downloaded: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/spring-framework-bom/4.3.7.RELEASE/spring-framework-bom-4.3.7.RELEASE.pom (0 B at 0.0 KB/sec)
Downloading: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/data/spring-data-releasetrain/Hopper-SR8/spring-data-releasetrain-Hopper-SR8.pom
Downloaded: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/data/spring-data-releasetrain/Hopper-SR8/spring-data-releasetrain-Hopper-SR8.pom (0 B at 0.0 KB/sec)
Downloading: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/data/build/spring-data-build/1.8.8.RELEASE/spring-data-build-1.8.8.RELEASE.pom
Downloaded: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/data/build/spring-data-build/1.8.8.RELEASE/spring-data-build-1.8.8.RELEASE.pom (0 B at 0.0 KB/sec)
Downloading: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/integration/spring-integration-bom/4.3.8.RELEASE/spring-integration-bom-4.3.8.RELEASE.pom
Downloaded: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/integration/spring-integration-bom/4.3.8.RELEASE/spring-integration-bom-4.3.8.RELEASE.pom (0 B at 0.0 KB/sec)
Downloading: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/security/spring-security-bom/4.1.4.RELEASE/spring-security-bom-4.1.4.RELEASE.pom
Downloaded: http://maven.aliyun.com/nexus/content/repositories/central/org/springframework/security/spring-security-bom/4.1.4.RELEASE/spring-security-bom-4.1.4.RELEASE.pom (0 B at 0.0 KB/sec)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact io.servicecomb:java-chassis-dependencies:pom:0.3.0-SNAPSHOT @ line 50, column 19
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.servicecomb.samples:bmi:0.3.0-SNAPSHOT (/home/ubuntu/ServiceComb-Java-Chassis/samples/bmi/pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Could not find artifact io.servicecomb:java-chassis-dependencies:pom:0.3.0-SNAPSHOT @ line 50, column 19 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by zenlinTechnofreak** [comment]
@zhuhoudong  have u fininshed `mvn install`  within java-chasis, if not, plz follow the guide in http://servicecomb.io/docs/quick-start/#Install Java development environment .

**Comment by zenlinTechnofreak** [comment]
@zhuhoudong Ensure u have installed the Java Chassis before running any samples, coresponding commands listed here,
`cd ServiceComb-Java-Chassis
mvn clean install -DskipTests -DskipITs
`

**Comment by zhuhoudong** [comment]
resolved！thanks
the reason is “”ServiceComb-Java-Chassis “ is not cleaned and compiled。
