### ISSUE TITLE
Zipkin's Docker image name is Wrong on web page

### ISSUE THREAD

**Issue by zhuhoudong** [ServiceComb/ServiceComb-Java-Chassis#156]
Zipkin's Docker image name is Wrong On the web page。

Wrong： openzipkin:zipkin
Correct：openzipkin/zipkin

**Comment by zhuhoudong** [comment]
<img width="671" alt="2017-09-21_104847" src="https://user-images.githubusercontent.com/31299631/30676823-ab55da50-9eba-11e7-93e4-069efc9bad5d.png">

![faststoneeditor2](https://user-images.githubusercontent.com/31299631/30676828-b12c0ce2-9eba-11e7-8247-b2450e202920.png)

**Comment by WillemJiang** [comment]
The bug is fixed, could you close this issue?

**Comment by zhuhoudong** [comment]
@WillemJiang ok,The bug is fixed, I close this issue.
