### ISSUE TITLE
Zipkin web page have no tracing information at all

### ISSUE THREAD

**Issue by zhuhoudong** [ServiceComb/ServiceComb-Java-Chassis#157]
I followed the guide of  《分布式调用链追踪》on web，but have no tracing information at all。

![image](https://user-images.githubusercontent.com/31299631/30696583-b9384906-9f0e-11e7-872f-6af633554ae8.png)

**Comment by WillemJiang** [comment]
You need to send some request first, otherwise the Zipkin doesn't have the traced information to display.

**Comment by seanyinx** [comment]
@zhuhoudong 
could you provide more details on how your project is configured?

**Comment by zenlinTechnofreak** [comment]
@zhuhoudong 

1.  Send some request to your app first;
2. Click `Find Traces` button to get detailed information;

Note that zipkin also have delay, suggest you to do clicking `Find traces` button several times.

**Comment by zhuhoudong** [comment]
补充一下：
1. webapp，calculator ，servicecenter，zipkin都在容器中运行。组网方式都是bridge.  云主机地址是：192.168.100.101
2. webapp，calculator的容器启动参数分别为：

  ENTRYPOINT java -jar bmi-webapp-tracing.jar -Ptracing -Dservicecomb.tracing.collector.address=http://192.168.100.101:9411

    ENTRYPOINT java -jar bmi-calculator-tracing.jar -Ptracing -Dcse.handler.chain.Provider.default=tracing-provider -Dservicecomb.tracing.collector.address=http://192.168.100.101:9411

3. 访问报错信息：

2017/9/23 下午5:48:262017-09-23 09:48:26,378 [INFO] watching microservice 6be7a0f09de911e7959a02efcacc0484 successfully, the chosen service center address is 192.168.100.101:30100 io.servicecomb.serviceregistry.client.http.ServiceRegistryClientImpl.lambda$watch$6(ServiceRegistryClientImpl.java:520)
2017/9/23 下午5:48:562017-09-23 09:48:56,262 [WARN] sc task interval changed from -1 to 30 io.servicecomb.serviceregistry.task.ServiceCenterTaskMonitor.beginCycle(ServiceCenterTaskMonitor.java:38)
2017/9/23 下午5:50:202017-09-23 09:50:20,301 [WARN] Dropped 1 spans due to ConnectException(Failed to connect to /127.0.0.1:9411) zipkin.reporter.AsyncReporter$BoundedAsyncReporter$1.onError(AsyncReporter.java:266)
2017/9/23 下午5:50:20java.net.ConnectException: Failed to connect to /127.0.0.1:9411
2017/9/23 下午5:50:20	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.RealCall.access$100(RealCall.java:33) ~[okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120) [okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.4.1.jar!/:?]
2017/9/23 下午5:50:20	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
2017/9/23 下午5:50:20	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
2017/9/23 下午5:50:20	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by WillemJiang** [comment]
Any update for this issue?

**Comment by zhuhoudong** [comment]
I resolved this problem by deploying bmi webapp and calculator in docker. 

Please refer the following  detail information .

1. 打包体质指数计算器 微服务的docker镜像并启动运行
假设zipkin在虚拟机192.168.100.101的9411端口下运行。
Step1. 编写dockerfile:
FROM anapsix/alpine-java:latest
ADD bmi-calculator-0.3.0-SNAPSHOT.jar /bmi-calculator-tracing.jar
EXPOSE 7781
ENTRYPOINT java $JAVA_OPTS -jar bmi-calculator-tracing.jar "-Ptracing"
Step2. 打包docker镜像：
root@i-wzmhsx68:/bmi-calculator-tracing# ls
bmi-calculator-0.3.0-SNAPSHOT.jar  dockerfile
root@i-wzmhsx68:/bmi-calculator-tracing# docker build -t="bmi-calculator-tracing" .
Step3. 启动docker容器：
docker run -d -e JAVA_OPTS="-Dservicecomb.tracing.collector.address=http://192.168.100.101:9411" bmi-calculator-tracing

2.  打包体质指数页面 微服务的docker镜像并启动运行
Step1. 编写dockerfile:
FROM anapsix/alpine-java:latest
ADD bmi-webapp-0.3.0-SNAPSHOT.jar /bmi-webapp-tracing.jar
ENTRYPOINT java $JAVA_OPTS -jar bmi-webapp-tracing.jar "-Ptracing"
Step2. 打包docker镜像：
root@i-wzmhsx68:/bmi-webapp-tracing# ls
bmi-webapp-0.3.0-SNAPSHOT.jar  dockerfile
root@i-wzmhsx68:/bmi-webapp-tracing# docker build -t="bmi-webapp-tracing" .
Step3. 启动docker容器：
docker run -d -e JAVA_OPTS="-Dservicecomb.tracing.collector.address=http://192.168.100.101:9411" bmi-webapp-tracing

**Comment by myVictor** [comment]
> 补充一下：
> **1. webapp，calculator ，servicecenter，zipkin都在容器中运行。组网方式都是bridge. 云主机地址是：192.168.100.101**
> 
> **2. 容器中的webapp和 calculator连接容器中的servicecenter（端口30100）是成功的。**
> 
> **3. webapp，calculator的容器启动参数分别为：**
> 
> ENTRYPOINT java -jar bmi-webapp-tracing.jar -Ptracing -Dservicecomb.tracing.collector.address=http://192.168.100.101:9411
> 
> ENTRYPOINT java -jar bmi-calculator-tracing.jar -Ptracing -Dcse.handler.chain.Provider.default=tracing-provider -Dservicecomb.tracing.collector.address=http://192.168.100.101:9411
> 
> **4. 访问报错信息：**
> 
> 2017/9/23 下午5:48:262017-09-23 09:48:26,378 [INFO] watching microservice 6be7a0f09de911e7959a02efcacc0484 successfully, the chosen service center address is 192.168.100.101:30100 io.servicecomb.serviceregistry.client.http.ServiceRegistryClientImpl.lambda$watch$6(ServiceRegistryClientImpl.java:520)
> 2017/9/23 下午5:48:562017-09-23 09:48:56,262 [WARN] sc task interval changed from -1 to 30 io.servicecomb.serviceregistry.task.ServiceCenterTaskMonitor.beginCycle(ServiceCenterTaskMonitor.java:38)
> 2017/9/23 下午5:50:202017-09-23 09:50:20,301 [WARN] Dropped 1 spans due to ConnectException(Failed to connect to /127.0.0.1:9411) zipkin.reporter.AsyncReporter$BoundedAsyncReporter$1.onError(AsyncReporter.java:266)
> 2017/9/23 下午5:50:20java.net.ConnectException: Failed to connect to /127.0.0.1:9411
> 2017/9/23 下午5:50:20	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.RealCall.access$100(RealCall.java:33) ~[okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120) [okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.4.1.jar!/:?]
> 2017/9/23 下午5:50:20	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
> 2017/9/23 下午5:50:20	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
> 2017/9/23 下午5:50:20	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

我也用这个例子自己实现了一个Edge Service（按照用户手册做的），问题是能查找服务信息，但是关系图无法生成出来，是什么原因？用的是URLMappedEdgeDispatcher
