### ISSUE TITLE
关于异常抛出问题

### ISSUE THREAD

**Issue by feelanture** [ServiceComb/ServiceComb-Java-Chassis#217]
在使用华为SC过程中，发现有个情况，就是通过服务中心注册服务后，业务通过服务汇总新调用这个服务的时候，如果被调用服务业务层抛出异常，经过SC后，业务异常被转换成了华为通用InvokationException 的509异常，而业务异常被屏蔽了。请问有什么方法可以将业务异常抛到外边呢？好让前台页面可以得到正确的业务异常`

**Comment by liubao68** [comment]
抛出异常这个内容不是所有的语言都支持，在跨语言通信的情形，一般采取的是开发者在返回值的结构里面封装好，比如gRPC, webservice等。 
在ServiceComb里面，任何给客户端返回的信息，必须包含在契约里面。即客户端能够拿到的信息，都必须是契约有描述的信息，如果契约没有描述，那么就不保证这些信息能够取到。Open API里面没有定义异常的结构体，所以也没有让业务抛出自己异常的做法。
那么要返回自定义消息怎么做了？
1. 义务捕获特定异常， 并且通过InvocationException抛出（自定错误码）。 可以通过契约或者@ApiResponse描述你的异常返回值的错误码和类型。先关例子可以在ServiceComb 的DEMO CodeFirstSpringMVC找到。
2.业务定义自己的ResponseWrapper类，里面包含status状态，以及对应的类型。

**Comment by feelanture** [comment]
请问，这两步一起实现异常抛出，还是两种方法？如果自定义自己的ResponseWrapper，这个如何做？

**Comment by liubao68** [comment]
两种可选的实现。从接口规范性的角度来讲，这个道理很简单：给客户端返回的任何消息，都能够通过结构化的语言描述出来。对于代码中出现的未知异常，或者程序内部逻辑错误是不应该返回出去的，这样造成内部信息泄露。

接口定义：
ResponsWrapper myService(RequestWrapper)

ResponsWrapper 定义：
class ResponsWrapper {
    int code;
    Person successResult;
    ErrorInfo failureInfo;
}
也就是说对外接口都不声明throws XXXExcpeiton。定义结果满足范式： returnValue methodName(arg1, arg2...)。 这样能够得到最大的跨语言支持。 对于java语言，抛出的异常，要捕获，并封装在returnValue里面。

**Comment by feelanture** [comment]
明白了，我自定义好了这个类，需要在哪里配置使得这个类生效？也就是如何让华为架构认识我这个自定义接口体？

**Comment by feelanture** [comment]
接口定义：
ResponsWrapper myService(RequestWrapper) 这个接口定义起什么作用？

**Comment by feelanture** [comment]
你的意思是这是业务人员开发业务要使用上述接口形式吗？

**Comment by liubao68** [comment]
是的。
