### ISSUE TITLE
关于DMS分布式队列时候用kafka开源标准客户端生产消费消息的问题

### ISSUE THREAD

**Issue by feelanture** [ServiceComb/ServiceComb-Java-Chassis#218]
准备用kafka标准客户端做异步消息处理，请问现在云环境支持的kafka版本是什么？谢谢！

**Comment by feelanture** [comment]
如果是可以用开源的kafka连接，能否给个例子，重点是如何和DMS对接，DMS授权如何通过kafka标准客户端输

**Comment by qizha** [comment]
这里是ServiceComb的开源社区，DMS的问题请在华为公有云上找相应支持人员。谢谢
