### ISSUE TITLE
关于dms的url如何获得

### ISSUE THREAD

**Issue by feelanture** [ServiceComb/ServiceComb-Java-Chassis#236]
项目中使用华为云的DMS分布式消息服务，创建队列后，准备用客户端连接队列，配置文件的说明是：#DMS kafka 接口地址,例如：dms-kafka.cn-north-1.myhwclouds.com:37000
bootstrap.servers=
请问，这个url如何获得，因为我在控制台里边找不到相关信息，所以不知道用什么地址和端口才能访问到我创建的队列。
这个地址是购买的某个服务器的地址，还是华为有统一的规范。我看例子是子域名，这个子域名是如何获取的，申请吗

**Comment by qizha** [comment]
这里是ServiceComb的开源社区，其他问题请直接联系相应的服务支持。谢谢
