### ISSUE TITLE
windows本地以可执行文件的方式运行Service Center，之后运行samples/bmi/calculator后registery failed，提示404 page not found？

### ISSUE THREAD

**Issue by MrStupidBird** [ServiceComb/ServiceComb-Java-Chassis#269]

**Comment by WillemJiang** [comment]
注册失败的日志是什么样的？
还有ServiceCenter启动之后能看一下监听的端口如何？

**Comment by eric-lee-ltk** [comment]
@MrStupidBird 请问您使用的service center的版本号是什么？建议使用最新的service center来运行： https://github.com/ServiceComb/service-center/releases/download/0.4.0/service-center-0.4.0-windows-amd64.zip

**Comment by MrStupidBird** [comment]
@WillemJiang @eric-lee-ltk 恩，应该是service center的问题，换了最新版本后问题已解决。
