### ISSUE TITLE
build failed due to metrics test not updated

### ISSUE THREAD

**Issue by seanyinx** [ServiceComb/ServiceComb-Java-Chassis#332]
```
Failed tests: 
  TestMetricsConfig.test:41 expected:<true> but was:<false>
```

**Comment by seanyinx** [comment]
caused by fix of https://github.com/ServiceComb/ServiceComb-Java-Chassis/issues/327

**Comment by WillemJiang** [comment]
This issue is fixed by 
https://github.com/ServiceComb/ServiceComb-Java-Chassis/commit/47414d0a61cbde901168bc79229161bfbbf39e85
